all:
#	clang++ -std=c++11 -Wc++11-extensions `pkg-config --libs --cflags gtkmm-3.0` main.cpp mg2toolbutton.cpp -o main
	g++ `pkg-config --libs --cflags gtkmm-3.0` main.cpp mg2toolbutton.cpp -o main
clean:
	rm main
